config/routes.rb
Rails.application.routes.draw do

  class ApiPrefixConstraint
    def initialize
      @allowed_subdomains = %w(api)
    end

    def matches?(request)
      request.path =~ /\A\/api\// || @allowed_subdomains.include?(request.subdomain)
    end
  end

  namespace :admin do
    devise_for :users

    resources :accounts, only: %i(new create edit update) do
      get :select, on: :member
      put :set_default, on: :member
    end
    resources :languages do
      put :set_default, on: :member
    end
    resources :questions do
      put :move, on: :member
    end
    resources :extra_questions do
      put :move, on: :member
    end
    resources :candidates
    resources :pages do
      put :move, on: :member
    end
    resources :parameters
    resources :submissions
    resources :customers
    resources :states do
      resources :districts
    end
    resources :users, only: %i(index create edit update destroy)

    root 'questions#index'
  end

  scope constraints: ApiPrefixConstraint.new do
    scope '(api)/:account/:language', as: :api, module: :api do
      resources :parameters, only: %i(index)
      resources :questions, only: %i(index)
      resources :extra_questions, only: %i(index)
      resources :candidates, only: %i(index)
      resources :customers, only: %i(create) do
        collection do
          get :current
          put :current, action: :update

          scope 'current', as: :customer do
            resources :submissions, only: %i(index update), controller: :customer_submissions
          end

          post :login
          delete :logout
          get :logout
        end
      end
      resources :passwords, only: %i(create update)
      resources :states, only: %i(index) do
        resources :districts, only: %i(index)
      end
      resources :districts, only: %i(index)
      resources :submissions, only: %i(index show update create) do
        put :left, on: :member
      end
    end
  end

  if Rails.application.config.app.oauth.present? && Rails.application.config.app.oauth.enabled.present?
    # Ominauth default prefix is "/auth"
    get '/auth/:provider/callback' => 'authentications#create', as: :oauth_callback, constraints: { provider: /#{Rails.application.config.app.oauth.enabled.join('|')}/ }
  end

  scope ':account/:language', as: :account do
    # Provide current_account_customer related methods
    devise_for :customers, only: [:passwords], controllers: {passwords: 'customers/passwords'}
  end

  get ':account/:publisher/:language/pages/:id' => 'pages#show', as: :page
  get ':comparsion_account/:account/:publisher/:language' => 'home#index', as: :compare_account
  get ':account/:publisher/:language' => 'home#index', as: :account_home
  post ':account/:language/submit' => 'api/submissions#create', as: :submission

  get 'ping-me' => 'home#ping'
  root 'home#root'
end

app/views/admin/pages/_form.html.erb
<% if @page.errors.present? %>
  <ul class="p-l-0 text-danger">
    <% @page.errors.keys.each do |k| %>
      <ul class="p-l-0"><%= k %>: <%= @page.errors[k].first %></ul>
    <% end %>
  </ul>
<% end %>
<%= fields_for @page do |f| %>
<fieldset class="form-group">
  <%= f.label :language_id %>
  <%= f.select :language_id, current_account.languages.order(:name).map { |e| [e.name, e.id] }, {}, class: 'form-control' %>
</fieldset>
<fieldset class="form-group">
  <%= f.label :kind %>
  <%= f.select :kind, Page::Kind.values.map { |e| [e.titlecase, e] }, {}, class: 'form-control' %>
  <small class="text-muted">Kind of menu item</small>
</fieldset>
<fieldset class="form-group">
  <%= f.label :name, 'Name *' %>
  <%= f.text_field :name, class: 'form-control', placeholder: 'Page name' %>
  <small class="text-muted">Page name in menu</small>
</fieldset>
<fieldset class="form-group">
  <%= f.label :path, 'Path or url *' %>
  <%= f.text_field :path, class: 'form-control', placeholder: 'about-us' %>
  <small class="text-muted">
    Kind "Page": Page path (e.g. "<i>about-us</i>")<br>
    Kind: "Link": Full url (e.g. "<i>http://http://www.societly.org/</i>").
  </small>
</fieldset>
<fieldset class="form-group">
  <%= f.label :hidden, 'Hide from menu' %>
  <%= f.check_box :hidden %>
</fieldset>

<p><strong>Fields for page:</strong></p>
<fieldset class="form-group">
  <%= f.label :title, 'Page title' %>
  <%= f.text_field :title, class: 'form-control', placeholder: 'About us' %>
  <small class="text-muted">Page title in browser titlebar. Also shown in Google search results and Facebook.</small>
</fieldset>
<fieldset class="form-group">
  <%= f.label :description, 'Page description' %>
  <%= f.text_field :description, class: 'form-control', placeholder: 'Short description of the page' %>
  <small class="text-muted">Page description for Facebook and Google search results.</small>
</fieldset>
<fieldset class="form-group">
  <%= f.label :content, 'Page content' %>
  <%= f.text_area :content, class: 'form-control', rows: '20' %>
  <small class="text-muted">Page content (HTML tags are supported).</small>
</fieldset>
<% end %>

app/views/admin/pages/_page.html.erb
<%= content_tag_for :tr, page do %>
  <td></td>
  <td><%= page.id %></td>
  <td><%= page.name %></td>
  <td><%= page.title %></td>
  <td><%= link_to page.path, (page.link? ? page.path : page_path(current_account.code, :default, page.language.code, page.path)), target: '_blank' %></td>
  <td><%= page.kind.titlecase %></td>
  <td><%= raw '&check;' if page.hidden? %></td>
  <td><%= lt(page.created_at) %></td>
  <td><%= lt(page.updated_at) %></td>
  <td>
    <%= link_to 'Edit', edit_admin_page_path(page) %>
    <%= link_to 'Delete', admin_page_path(page), data: {method: :delete, confirm: 'Are you sure you want to delete this page?'} %>
    <%= link_to '&#9650;'.html_safe, move_admin_page_path(page, language: @language.try(:code), direction: :up), remote: true, method: :put, class: 'move-up', title: 'Move up' %>
    <%= link_to '&#9660;'.html_safe, move_admin_page_path(page, language: @language.try(:code), direction: :down), remote: true, method: :put, class: 'move-down', title: 'Move down' %>
  </td>
<% end %>

app/views/admin/pages/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>Edit page</h1>

    <%= form_for [:admin, @page] do |f| %>
      <%= render partial: 'form' %>
      <button type="submit" class="btn btn-primary">Save page</button>
    <% end %>
  </div>
</div>

app/views/admin/pages/index.html.erb
<ul class="nav nav-tabs" style="margin-bottom: 20px;">
  <% @languages.each do |lang| %>
    <li class="nav-item">
      <%= link_to lang.name, admin_pages_path(language: lang.code), class: ['nav-link', ('active' if lang.code == @language.try(:code))] %>
    </li>
  <% end %>
</ul>

<h1>
  Account pages
  
  <%= link_to 'Add page', new_admin_page_path(language: @language.try(:code)), class: 'btn btn-success pull-right' %>
</h1>

<table class="table table-bordered sortable">
<thead>
  <tr>
    <th title="Position in menu">#</th>
    <th>ID</th>
    <th>Name</th>
    <th>Title</th>
    <th>Path</th>
    <th>Kind</th>
    <th>Hidden</th>
    <th>Created at</th>
    <th>Updated at</th>
    <th></th>
  </tr>
</thead>
<%= render partial: 'page', collection: @pages %>
</table>

app/views/admin/pages/move.js.erb
jQuery(function($) {
  <% if @old_position != @new_position %>
    var row  = $('#<%= dom_id(@page) %>');
    <% if @old_position.to_i > @new_position.to_i %>
      row.insertBefore(row.prev());
    <% else %>
      row.insertAfter(row.next());
    <% end %>
  <% end %>
});

app/views/admin/pages/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>Add page</h1>

    <%= form_for [:admin, @page] do |f| %>
      <%= render partial: 'form' %>
      <button type="submit" class="btn btn-primary">Create page</button>
    <% end %>
  </div>
</div>