config/routes.rb
Rails.application.routes.draw do

  class ApiPrefixConstraint
    def initialize
      @allowed_subdomains = %w(api)
    end

    def matches?(request)
      request.path =~ /\A\/api\// || @allowed_subdomains.include?(request.subdomain)
    end
  end

  namespace :admin do
    devise_for :users

    resources :accounts, only: %i(new create edit update) do
      get :select, on: :member
      put :set_default, on: :member
    end
    resources :languages do
      put :set_default, on: :member
    end
    resources :questions do
      put :move, on: :member
    end
    resources :extra_questions do
      put :move, on: :member
    end
    resources :candidates
    resources :pages do
      put :move, on: :member
    end
    resources :parameters
    resources :submissions
    resources :customers
    resources :states do
      resources :districts
    end
    resources :users, only: %i(index create edit update destroy)

    root 'questions#index'
  end

  scope constraints: ApiPrefixConstraint.new do
    scope '(api)/:account/:language', as: :api, module: :api do
      resources :parameters, only: %i(index)
      resources :questions, only: %i(index)
      resources :extra_questions, only: %i(index)
      resources :candidates, only: %i(index)
      resources :customers, only: %i(create) do
        collection do
          get :current
          put :current, action: :update

          scope 'current', as: :customer do
            resources :submissions, only: %i(index update), controller: :customer_submissions
          end

          post :login
          delete :logout
          get :logout
        end
      end
      resources :passwords, only: %i(create update)
      resources :states, only: %i(index) do
        resources :districts, only: %i(index)
      end
      resources :districts, only: %i(index)
      resources :submissions, only: %i(index show update create) do
        put :left, on: :member
      end
    end
  end

  if Rails.application.config.app.oauth.present? && Rails.application.config.app.oauth.enabled.present?
    # Ominauth default prefix is "/auth"
    get '/auth/:provider/callback' => 'authentications#create', as: :oauth_callback, constraints: { provider: /#{Rails.application.config.app.oauth.enabled.join('|')}/ }
  end

  scope ':account/:language', as: :account do
    # Provide current_account_customer related methods
    devise_for :customers, only: [:passwords], controllers: {passwords: 'customers/passwords'}
  end

  get ':account/:publisher/:language/pages/:id' => 'pages#show', as: :page
  get ':comparsion_account/:account/:publisher/:language' => 'home#index', as: :compare_account
  get ':account/:publisher/:language' => 'home#index', as: :account_home
  post ':account/:language/submit' => 'api/submissions#create', as: :submission

  get 'ping-me' => 'home#ping'
  root 'home#root'
end

app/views/layouts/admin/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <!-- Required meta tags always come first -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  
  <title>Societly</title>
  <%= stylesheet_link_tag 'admin/admin', media: 'all' %>
  <%= csrf_meta_tags %>
</head>

<body>
  <nav class="navbar navbar-light bg-faded">
    <div class="container">
      <a class="navbar-brand" href="#">Societly</a>
      <ul class="nav navbar-nav">
        <%= content_tag :li, class: ['nav-item', ('active' if request.path.starts_with?('/admin/questions'))] do %>
          <%= link_to 'Statements', admin_questions_path, class: 'nav-link' %>
        <% end %>
        <%= content_tag :li, class: ['nav-item', ('active' if request.path.starts_with?('/admin/extra_questions'))] do %>
          <%= link_to 'Extra questions', admin_extra_questions_path, class: 'nav-link' %>
        <% end %>
        <%= content_tag :li, class: ['nav-item', ('active' if request.path.starts_with?('/admin/candidates'))] do %>
          <%= link_to 'Candidates', admin_candidates_path, class: 'nav-link' %>
        <% end %>
        <%= content_tag :li, class: ['nav-item', ('active' if request.path.starts_with?('/admin/parameters'))] do %>
          <%= link_to 'Spider dimensions', admin_parameters_path, class: 'nav-link' %>
        <% end %>
        <%= content_tag :li, class: ['nav-item', ('active' if request.path.starts_with?('/admin/states'))] do %>
          <%= link_to 'States', admin_states_path, class: 'nav-link' %>
        <% end %>
        <%= content_tag :li, class: ['nav-item', ('active' if request.path.starts_with?('/admin/submissions'))] do %>
          <%= link_to 'Submissions', admin_submissions_path, class: 'nav-link' %>
        <% end %>
        <%= content_tag :li, class: ['nav-item', ('active' if request.path.starts_with?('/admin/customers'))] do %>
          <%= link_to 'Customers', admin_customers_path, class: 'nav-link' %>
        <% end %>
      </ul>
      
      <ul class="nav navbar-nav pull-right">
        <%= content_tag :li, class: ['nav-item', ('active' if request.path.starts_with?('/admin/users'))] do %>
          <%= link_to 'Users', admin_users_path, class: 'nav-link' %>
        <% end %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_account.name %>
          </a>
          <div class="dropdown-menu" aria-labelledby="dropdownMenu1">
            <% @accounts.each do |account| %>
              <%= link_to "#{account.name}#{ ' (default)' if account.default? }", select_admin_account_path(account), class: 'dropdown-item' %>
            <% end %>
            <div class="dropdown-divider"></div>
            <%= link_to 'Languages', admin_languages_path, class: 'dropdown-item' %>
            <%= link_to 'Pages', admin_pages_path, class: 'dropdown-item' %>
            <%= link_to 'Edit account', edit_admin_account_path(current_account), class: 'dropdown-item' %>
            <%= link_to 'Set as default account', set_default_admin_account_path(current_account), class: 'dropdown-item', data: {method: :put, confirm: 'Default account is shown for user who are entering to site without account code. Are you sure you want to set this account as default?'} unless current_account.default? %>
            <div class="dropdown-divider"></div>
            <%= link_to 'Create account', new_admin_account_path, class: 'dropdown-item' %>
          </div>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign out', destroy_admin_user_session_path, class: 'nav-link' %>
        </li>
      </ul>
    </div>
  </nav>
    
  <div class="container admin-content">
    <% if flash.alert %><div class="alert alert-warning"><%= flash.alert %></div><% end %>
    <% if flash.notice %><div class="alert alert-success"><%= flash.notice %></div><% end %>
    
    <%= yield %>
  </div>

  <%= javascript_include_tag 'admin/admin' %>
</body>
</html>

app/views/layouts/admin/public.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Societly login</title>

    <%= stylesheet_link_tag 'admin/admin', media: 'all' %>
  </head>

  <body class="public">

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>