config/routes.rb
Rails.application.routes.draw do

  class ApiPrefixConstraint
    def initialize
      @allowed_subdomains = %w(api)
    end

    def matches?(request)
      request.path =~ /\A\/api\// || @allowed_subdomains.include?(request.subdomain)
    end
  end

  namespace :admin do
    devise_for :users

    resources :accounts, only: %i(new create edit update) do
      get :select, on: :member
      put :set_default, on: :member
    end
    resources :languages do
      put :set_default, on: :member
    end
    resources :questions do
      put :move, on: :member
    end
    resources :extra_questions do
      put :move, on: :member
    end
    resources :candidates
    resources :pages do
      put :move, on: :member
    end
    resources :parameters
    resources :submissions
    resources :customers
    resources :states do
      resources :districts
    end
    resources :users, only: %i(index create edit update destroy)

    root 'questions#index'
  end

  scope constraints: ApiPrefixConstraint.new do
    scope '(api)/:account/:language', as: :api, module: :api do
      resources :parameters, only: %i(index)
      resources :questions, only: %i(index)
      resources :extra_questions, only: %i(index)
      resources :candidates, only: %i(index)
      resources :customers, only: %i(create) do
        collection do
          get :current
          put :current, action: :update

          scope 'current', as: :customer do
            resources :submissions, only: %i(index update), controller: :customer_submissions
          end

          post :login
          delete :logout
          get :logout
        end
      end
      resources :passwords, only: %i(create update)
      resources :states, only: %i(index) do
        resources :districts, only: %i(index)
      end
      resources :districts, only: %i(index)
      resources :submissions, only: %i(index show update create) do
        put :left, on: :member
      end
    end
  end

  if Rails.application.config.app.oauth.present? && Rails.application.config.app.oauth.enabled.present?
    # Ominauth default prefix is "/auth"
    get '/auth/:provider/callback' => 'authentications#create', as: :oauth_callback, constraints: { provider: /#{Rails.application.config.app.oauth.enabled.join('|')}/ }
  end

  scope ':account/:language', as: :account do
    # Provide current_account_customer related methods
    devise_for :customers, only: [:passwords], controllers: {passwords: 'customers/passwords'}
  end

  get ':account/:publisher/:language/pages/:id' => 'pages#show', as: :page
  get ':comparsion_account/:account/:publisher/:language' => 'home#index', as: :compare_account
  get ':account/:publisher/:language' => 'home#index', as: :account_home
  post ':account/:language/submit' => 'api/submissions#create', as: :submission

  get 'ping-me' => 'home#ping'
  root 'home#root'
end

app/models/state.rb
class State < ActiveRecord::Base

  include SoftDeleteable
  include Translateable

  belongs_to :account
  has_many :districts, dependent: :destroy

  validates :account_id, presence: true
  validates :name, length: {maximum: 255}, presence: true
  validates :code, presence: true, uniqueness: {scope: [:account_id, :deleted_at]}

  scope :sorted, -> { order(:name) }

  def name=(translated_names)
    set_translations_for(:name, translated_names, account.languages)
  end
end

app/controllers/admin/states_controller.rb
class Admin::StatesController < Admin::AdminController

  before_action :require_language

  def index
    @states = current_account.states.order(:name)
  end
  
  def new
    @state = current_account.states.build
  end
  
  def create
    @state = current_account.states.build
    @state.attributes = state_params
    
    if @state.save
      redirect_to admin_states_path, notice: 'State has been created'
    else
      flash.now.alert = 'Please fill in required fields'
      render action: 'new'
    end
  end
  
  def edit
    @state = current_account.states.find(params[:id])
  end
  
  def update
    @state = current_account.states.find(params[:id])
    
    if @state.update_attributes(state_params)
      redirect_to admin_states_path, notice: 'State has been updated'
    else
      flash.now.alert = 'Please fill in required fields'
      render action: 'edit'
    end
  end
  
  def destroy
    current_account.states.find(params[:id]).destroy
    redirect_to admin_states_path, notice: 'State has been deleted'
  end
  
  private
  
  def state_params
    params.required(:state).permit(:code, :name).tap do |whitelist|
      whitelist[:name] = params[:state][:name]
    end
  end
end

app/controllers/api/states_controller.rb
class Api::StatesController < Api::ApiController

  before_action :set_public_cache

  def index
    states = @account.states.includes(:translations).sorted
    states = states.where(id: @account.used_state_ids) unless params.key?(:all)
    render json: paginate_with_links(states).map { |state| state_json(state) }
  end

  private

  def state_json(state)
    state.serializable_hash(only: %i(id code)).merge(
      name: state.translation_for_with_default(:name, @language)
    )
  end
end

app/views/admin/states/_form.html.erb
<%= fields_for @state, {}, builder: TranslateableFormBuilder do |f| %>
<fieldset class="form-group">
  <%= f.label :code, 'Code *' %>
  <%= f.text_field :code, class: 'form-control', placeholder: 'Unique code eg CA' %>
  <small class="text-muted">State code</small>
</fieldset>
<fieldset class="form-group">
  <%= f.label :name %>
  <%= f.translatable_text_field :name, class: 'form-control', placeholder: 'Name' %>
</fieldset>
<% end %>

app/views/admin/states/_state.html.erb
<tr>
  <td><%= state.id %></td>
  <td><%= state.code %></td>
  <td><%= state.name %></td>
  <td><%= lt(state.created_at) %></td>
  <td><%= lt(state.updated_at) %></td>
  <td>
    <%= link_to 'Edit', edit_admin_state_path(state) %>
    <%= link_to "Districts (#{state.districts.count})", admin_state_districts_path(state) %>
    <%= link_to 'Delete', admin_state_path(state), data: {method: :delete, confirm: 'Are you sure you want to delete this state?'} %>
  </td>
</tr>

app/views/admin/states/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>Edit state</h1>

    <%= form_for [:admin, @state] do |f| %>
      <%= render partial: 'form' %>
      <button type="submit" class="btn btn-primary">Save state</button>
    <% end %>
  </div>
</div>

app/views/admin/states/index.html.erb
<h1>
  States <small>(<%= @states.count %>)</small>

  <%= link_to 'Add state', new_admin_state_path, class: 'btn btn-success pull-right' %>
</h1>

<table class="table table-bordered">
<thead>
  <tr>
    <th>#</th>
    <th>Code</th>
    <th>Name</th>
    <th>Created at</th>
    <th>Updated at</th>
    <th></th>
  </tr>
</thead>
<%= render partial: 'state', collection: @states %>
</table>

app/views/admin/states/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>Add state</h1>
    
    <%= form_for [:admin, @state] do |f| %>
      <%= render partial: 'form' %>
      <button type="submit" class="btn btn-primary">Create state</button>
    <% end %>
  </div>
</div>