config/routes.rb
Rails.application.routes.draw do

  class ApiPrefixConstraint
    def initialize
      @allowed_subdomains = %w(api)
    end

    def matches?(request)
      request.path =~ /\A\/api\// || @allowed_subdomains.include?(request.subdomain)
    end
  end

  namespace :admin do
    devise_for :users

    resources :accounts, only: %i(new create edit update) do
      get :select, on: :member
      put :set_default, on: :member
    end
    resources :languages do
      put :set_default, on: :member
    end
    resources :questions do
      put :move, on: :member
    end
    resources :extra_questions do
      put :move, on: :member
    end
    resources :candidates
    resources :pages do
      put :move, on: :member
    end
    resources :parameters
    resources :submissions
    resources :customers
    resources :states do
      resources :districts
    end
    resources :users, only: %i(index create edit update destroy)

    root 'questions#index'
  end

  scope constraints: ApiPrefixConstraint.new do
    scope '(api)/:account/:language', as: :api, module: :api do
      resources :parameters, only: %i(index)
      resources :questions, only: %i(index)
      resources :extra_questions, only: %i(index)
      resources :candidates, only: %i(index)
      resources :customers, only: %i(create) do
        collection do
          get :current
          put :current, action: :update

          scope 'current', as: :customer do
            resources :submissions, only: %i(index update), controller: :customer_submissions
          end

          post :login
          delete :logout
          get :logout
        end
      end
      resources :passwords, only: %i(create update)
      resources :states, only: %i(index) do
        resources :districts, only: %i(index)
      end
      resources :districts, only: %i(index)
      resources :submissions, only: %i(index show update create) do
        put :left, on: :member
      end
    end
  end

  if Rails.application.config.app.oauth.present? && Rails.application.config.app.oauth.enabled.present?
    # Ominauth default prefix is "/auth"
    get '/auth/:provider/callback' => 'authentications#create', as: :oauth_callback, constraints: { provider: /#{Rails.application.config.app.oauth.enabled.join('|')}/ }
  end

  scope ':account/:language', as: :account do
    # Provide current_account_customer related methods
    devise_for :customers, only: [:passwords], controllers: {passwords: 'customers/passwords'}
  end

  get ':account/:publisher/:language/pages/:id' => 'pages#show', as: :page
  get ':comparsion_account/:account/:publisher/:language' => 'home#index', as: :compare_account
  get ':account/:publisher/:language' => 'home#index', as: :account_home
  post ':account/:language/submit' => 'api/submissions#create', as: :submission

  get 'ping-me' => 'home#ping'
  root 'home#root'
end

app/models/submission.rb
class Submission < ActiveRecord::Base

  serialize :answers, JSON
  serialize :extra_questions, JSON
  serialize :location_data, JSON

  belongs_to :account
  belongs_to :state
  belongs_to :district
  belongs_to :customer
  belongs_to :comparision_account, class_name: 'Account'

  validates :account_id, presence: true
  validates :publisher, :remote_ip, :title, :full_name, :email, :zip, :facebook, :twitter,
    :gender, :year_of_birth, :ethnicity, :education, :phone, :external_ref, length: {maximum: 255}, allow_blank: true

  before_create :set_hash
  after_validation :set_location_data, on: :create

  def title
    read_attribute(:title) || (I18n.t('submissions.default_title', date: I18n.l(created_at.to_date, format: :long)) if created_at)
  end

  def db_title
    read_attribute(:title)
  end

  private

  def set_hash
    begin
      self[:client_hash] = SecureRandom.hex(32).upcase
    end while Submission.where(client_hash: self[:client_hash]).exists?
  end

  # Fill location information by GeoIp data.
  def set_location_data
    # if remote_ip.present?
    #   location = GeoipLocation.find_by_ip(remote_ip)

    #   if location.try(:found?)
    #     self.location_data = {
    #       country_code: location.country.iso_code,
    #       country_name: location.country.name,
    #       subdivision_code: location.subdivisions.first.try(:iso_code),
    #       subdivision_name: location.subdivisions.first.try(:name),
    #       city: location.city.name,
    #       latitude: location.location.latitude,
    #       longitude: location.location.longitude
    #     }.reject { |_, v| v.blank?}
    #   end
    # end
  rescue => e
    logger.error "#{e.message}\n#{e.backtrace[0..7].join("\n  ")}"
    true
  end
end

app/controllers/admin/submissions_controller.rb
require 'csv'

class Admin::SubmissionsController < Admin::AdminController

  before_action :require_language

  def index
    @submissions = current_account.submissions.includes(:state, :district).order('id DESC')

    respond_to do |format|
      format.html do
        @submissions = @submissions.paginate(page: params[:page])
      end
      format.csv do
        # TODO: Improve performance
        @include_candidates = params.key?(:include_candidates)
        @questions = current_account.questions.sorted
        @extra_questions = current_account.extra_questions.sorted
        @candidates = current_account.candidates.by_level('country').includes(:candidate_question_answers).order(:name) if @include_candidates
        @language = current_account.languages.default_language.first
        headers['Content-Disposition'] = "attachment; filename=\"societly-#{current_account.name.downcase}-submissions-#{Time.now.strftime("%Y%m%d%H%M")}.csv\""
        headers['Content-Type'] ||= 'text/csv'
      end
    end
  end

  def show
    @submission = current_account.submissions.find(params[:id])
    @questions_hash = current_account.questions.each_with_object({}) { |q, h| h[q.id] = q }
  end
end

app/controllers/api/submissions_controller.rb
class Api::SubmissionsController < Api::ApiController
  respond_to :json
  skip_before_action :load_language, only: [:show, :update, :left]

  def show
    submission = @account.submissions.find_by!(client_hash: params[:id])
    render json: submission_json(submission)
  end

  def create
    submission = @account.submissions.build(submission_attributes)
    submission.customer = current_account_customer if current_account_customer && current_account_customer.account_id == @account.id

    if submission.save
      render json: submission_create_json(submission), status: :created
    else
      render_error_response 'An error occurred when creating this submission. Please review the fields.', submission.errors
    end
  end

  def update
    submission = @account.submissions.find_by!(client_hash: params[:id])

    # When current customer is present and confirm_hash is valid (and not expired) then add current_customer to current submission.
    if submission.customer_id.blank? && current_account_customer && current_account_customer.account_id == @account.id
      message = begin
        verifier.verify(params[:confirm_hash]) if params[:confirm_hash].present?
      rescue => e
        logger.debug e.inspect
        nil
      end

      if message && message['id'] == submission.id && message['expires'] >= Time.now
        submission.update_attribute(:customer_id, current_account_customer.id)
      end
    end

    render json: submission_customer_json(submission)
  end

  def left
    submission = @account.submissions.find_by(client_hash: params[:id])
    submission.touch(:left_page_at) if submission && submission.left_page_at.blank?

    render json: {}
  end

  private

  def submission_attributes
    params.required(:submission).permit(
      :publisher, :seconds_to_result, :start_to_result, :full_name, :email, :zip, :facebook, :twitter,
      :gender, :year_of_birth, :ethnicity, :education, :phone, :state_id, :district_id, :external_ref,
      :comparision_account
    ).tap do |whitelisted|
      whitelisted[:language_code] = params.fetch(:language)
      whitelisted[:answers] = params[:submission][:answers]
      whitelisted[:extra_questions] = params[:submission][:extra_questions]
      whitelisted[:open_page_at] = begin DateTime.parse(params[:submission][:open_page_at]) rescue nil; end
      whitelisted[:comparision_account] = Account.find_by(code: params.fetch(:comparision_account))
    end.merge(remote_ip: request.remote_ip, user_agent: request.env['HTTP_USER_AGENT'])
  end

  def submission_json(submission)
    submission.serializable_hash(
      only: %i(state_id district_id answers extra_questions external_ref account_id comparision_account_id)
    ).merge(
      submission_customer_json(submission)
    )
  end

  def submission_customer_json(submission)
    if submission.customer && !submission.customer.private?
      {
        title: submission.title,
        customer: {
          full_name: submission.customer.full_name.presence,
          image: (submission.customer.public_url if submission.customer.image.present?)
        }
      }
    else
      {}
    end
  end

  def submission_create_json(submission)
    {client_hash: submission.client_hash}.tap do |json|
      # Add confirm_hash if submission hasn't customer object
      json[:confirm_hash] = verifier.generate(id: submission.id, expires: Time.now + 1.day) if submission.customer.blank?
    end.merge(
      submission_customer_json(submission)
    )
  end

  # Message verifier.
  def verifier
    @verifier ||= ActiveSupport::MessageVerifier.new(Rails.application.secrets.secret_key_base, digest: 'SHA256', serializer: JSON)
  end
end

app/helpers/admin/submissions_helper.rb
module Admin::SubmissionsHelper

  # Calculate distance between candidate and submitter
  #   submission - hash of submission answers where key is the question id
  def candidate_distance(candidate, answers)
    distance_sum = BigDecimal.new('0.0')
    count = 0
    balance_count = BigDecimal.new('0.0')

    candidate.candidate_question_answers.each do |candidate_answer|
      answer = answers[candidate_answer.question_id]

      if answer && answer['answer']
         distance_sum += (answer['answer'] - (candidate_answer.answer || 0)).abs * (answer['balance'] || 1)
         balance_count +=  answer['balance'] || 1
         count += 1
      end
    end

    if count == 0
      0
    else
      (100.0 - (distance_sum / (count * (balance_count / count)))).round
    end
  rescue => e
    logger.error "#{e.message}\n#{e.backtrace[0..7].join("\n  ")}"
    ''
  end
end

app/views/admin/submissions/_submission.html.erb
<tr>
  <td><%= submission.id %></td>
  <td><%= lt(submission.created_at) %></td>
  <td><%= submission.language_code %></td>
<%
=begin%>
 
  <td><%= submission.remote_ip %></td>
  <td><%= submission.location_data['country_name'] if submission.location_data.present? %></td>
  <td><%= submission.location_data['city'] if submission.location_data.present? %></td>
   
<%
=end%>
  <td><%= submission.publisher.try(:capitalize) %></td>
  <td><%= submission.full_name %></td>
  <td><%= mail_to submission.email if submission.email %></td>
  <td><%= link_to 'Show', admin_customer_path(submission.customer_id) if submission.customer_id.present? %></td>
  <td><%= link_to 'Details', admin_submission_path(submission) %></td>
</tr>

app/views/admin/submissions/index.csv.erb
<%
  header = [
    'id',
    'Publisher',
    'Language',
    'Submitted',
    'External ref',
    #'IP address',
    #'Country code',
    #'Country name',
    #'Subdiv. code',
    #'Subdiv. name',
    #'City',
    #'Latitude',
    #'Longitude',
    'Start to result',
    'Seconds to result',
    'Open page at',
    'Left page at',
    'Name',
    'Gender',
    'Year of birth',
    'Race/ethnicity',
    'ZIP code',
    'State',
    'District',
    'Education',
    'Email',
    'Cell phone',
    'Facebook',
    'Twitter',
    'Customer id',
    'Title',
  ]

  @questions.each do |q|
    header << "S ID #{q.id} - answer"
    header << "S ID #{q.id} - balance"
  end

  @extra_questions.each do |q|
    header << "EQ ID #{q.id}"
  end

  if @include_candidates
    @candidates.each do |c|
      header << c.name
    end
  end

  submissions_csv = CSV.generate(col_sep: ';') do |csv|
    # header row
    csv << header
    # data rows
    @submissions.find_each do |submission|
      row = [
        submission.id,
        submission.publisher.try(:capitalize),
        submission.language_code,
        lt(submission.created_at),
        submission.external_ref,
        # submission.remote_ip
      ]
      # if submission.location_data.present?
      #   %w(country_code country_name subdivision_code subdivision_name city latitude longitude).each do |k|
      #     row << submission.location_data[k]
      #   end
      # else
      #   row += Array.new(7)
      # end

      row += [
        submission.start_to_result,
        submission.seconds_to_result,
        lt(submission.open_page_at),
        lt(submission.left_page_at),
        submission.full_name,
        submission.gender,
        submission.year_of_birth,
        submission.ethnicity,
        submission.zip,
        submission.state.try(:name),
        submission.district.try(:name),
        submission.education,
        submission.email,
        submission.phone,
        submission.facebook,
        submission.twitter,
        submission.customer_id,
        submission.db_title
      ]

      answers = submission.answers.each_with_object({}) { |answer, h| h[answer['question_id']] = answer }

      @questions.each do |q|
        if answers[q.id]
          row << answers[q.id]['answer']
          row << answers[q.id]['balance']
        else
          row += Array.new(2)
        end
      end

      @extra_questions.each do |q|
        answer = (submission.extra_questions || {})[q.id.to_s]
        if answer.present?
          row << (q.option_value_for(answer, @language).presence || answer)
        else
          row << ''
        end
      end

      if @include_candidates
        @candidates.each do |c|
          row << candidate_distance(c, answers)
        end
      end

      csv << row
    end
  end
%>
<%= raw submissions_csv %>

app/views/admin/submissions/index.html.erb
<h1>
  Submissions <small>(<%= @submissions.total_entries %>)</small>
  
  <div class="btn-group pull-right">
  <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Actions
  </button>
  <div class="dropdown-menu">
    <%= link_to 'Download CSV', admin_submissions_path(format: :csv), class: 'dropdown-item' %>
    <%= link_to 'Download CSV (with candidates)', admin_submissions_path(format: :csv, include_candidates: true), class: 'dropdown-item' %>
  </div>
</div>
</h1>

<table class="table table-bordered">
<thead>
  <tr>
    <th>#</th>
    <th>Submitted</th>
    <th>Language</th>
    <%
=begin%>
 <th>IP address</th>
    <th>Country</th>
    <th>City</th> 
<%
=end%>
    <th>Publisher</th>
    <th>Name</th>
    <th>Email</th>
    <th>Customer</th>
    <th></th>
  </tr>
</thead>
<%= render partial: 'submission', collection: @submissions %>
</table>

<%= will_paginate @submissions, renderer: ::BootstrapPagination::Rails %>

app/views/admin/submissions/show.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>
      Submission details
      <small><small><%= link_to 'result page', account_home_path(current_account.code, @submission.publisher.to_s, @submission.language_code, anchor: "results/list/#{@submission.client_hash}"), target: '_blank' %></small></small>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <dl class="dl-horizontal col-md-12 col-lg-6">
      <%= list_row 'Customer', (link_to('Show', admin_customer_path(@submission.customer_id)) if @submission.customer_id.present?), label_html: {class: 'col-md-5'} %>
      <%= list_row 'Name', @submission.full_name, label_html: {class: 'col-md-5'} %>
      <%= list_row 'Gender', @submission.gender, label_html: {class: 'col-md-5'} %>
      <%= list_row 'Year of birth', @submission.year_of_birth, label_html: {class: 'col-md-5'} %>
      <%= list_row 'Race/ethnicity', @submission.ethnicity, label_html: {class: 'col-md-5'} %>
      <%= list_row 'ZIP code', @submission.zip, label_html: {class: 'col-md-5'} %>
      <%= list_row 'State', @submission.state.name, label_html: {class: 'col-md-5'} if @submission.state %>
      <%= list_row 'District', @submission.district.name, label_html: {class: 'col-md-5'} if @submission.district %>
      <%= list_row 'Education', @submission.education, label_html: {class: 'col-md-5'} %>
      <%= list_row 'Email', @submission.email, label_html: {class: 'col-md-5'} %>
      <%= list_row 'Cell phone', @submission.phone, label_html: {class: 'col-md-5'} %>
      <%= list_row 'Facebook', @submission.facebook, label_html: {class: 'col-md-5'} %>
      <%= list_row 'Twitter', @submission.twitter, label_html: {class: 'col-md-5'} %>
    </dl>
    <dl class="dl-horizontal col-md-12 col-lg-6">
      <%= list_row 'Title', @submission.db_title, label_html: {class: 'col-md-5'} %>
      <%= list_row 'Publisher', @submission.publisher.try(:capitalize), label_html: {class: 'col-md-5'} %>
      <%= list_row 'Language', @submission.language_code, label_html: {class: 'col-md-5'} %>
      <%= list_row 'Submitted', lt(@submission.created_at), label_html: {class: 'col-md-5'} %>
      <%= list_row 'External ref', @submission.external_ref, label_html: {class: 'col-md-5'} %>
      <%
=begin%>
 <%= list_row 'IP address', @submission.remote_ip, label_html: {class: 'col-md-5'} %> 
<%
=end%>
      <%= list_row 'Start to result', @submission.start_to_result, label_html: {class: 'col-md-5'} %>
      <%= list_row 'Seconds to result', @submission.seconds_to_result, label_html: {class: 'col-md-5'} %>
      <%= list_row 'Open page at', lt(@submission.open_page_at), label_html: {class: 'col-md-5'} %>
      <%= list_row 'Left page at', lt(@submission.left_page_at), label_html: {class: 'col-md-5'} %>
    </dl>
  </div>
  <%
=begin%>
 <% if @submission.location_data.present? %>
    <div class="col-md-12">
      <h3>Location details</h3>
      <dl class="dl-horizontal col-md-12 col-lg-6">
        <% %w(country_code country_name subdivision_code subdivision_name city latitude longitude).each do |k| %>
          <%= list_row k.humanize, @submission.location_data[k], label_html: {class: 'col-md-5'} if @submission.location_data[k].present? %>
        <% end %>
      </dl>
    </div>
  <% end %> 
<%
=end%>
</div>

<% if @submission.answers.present? %>
<div class="row">
  <div class="col-md-12">
    <h3>Statement answers</h3>
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th>#</th>
          <th>Statement</th>
          <th>Answer</th>
          <th>Balance</th>
        </tr>
      </thead>
      <tbody>
        <% @submission.answers.each do |a| %>
          <tr>
            <td><%= a['question_id'] %></td>
            <td><%= @questions_hash[a['question_id']].try(:name) %></td>
            <td><%= a['answer'] %></td>
            <td><%= a['balance'] %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<% end %>

<% if @submission.extra_questions.present? %>
<div class="row">
  <div class="col-md-12">
    <h3>Extra questions</h3>
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th>#</th>
          <th>Question</th>
          <th>Answer</th>
        </tr>
      </thead>
      <tbody>
        <% language = current_account.languages.default_language.first %>
        <% @submission.extra_questions.each do |k, v| %>
          <% q = current_account.extra_questions.find_by_id(k)  %>
          <tr>
            <td><%= q.try(:id) %></td>
            <td><%= q.try(:name) %></td>
            <td><%= q.option_value_for(v, language).presence || v %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<% end %>